### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by ghost** [celestinolopes/dashboard-flutter-web#1]
1. Add images screenshots of the project, on repository.
2. Add title and description on readme of the repository, for the people to know what is, what are doing...
3. Create a new branch, so the community can contribute ...

**Comment by celestinolopes** [comment]
Changes have been made. Thanks @Romavic

**Comment by ghost** [comment]
@celestinolopes now you can, to close this issue... good work.

**Comment by celestinolopes** [comment]
@Romavic 👊
